### ISSUE TITLE
Analytics collector fails to query database list even when data base exists

### ISSUE THREAD

**Issue by pradeepna** [khilan2goel/AnalyticsCollectors#10]
When I run the collector for the first time, it fails with the following error:

Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at AnalyticsCollector.AzureDataExplorerService.get_DatabaseName() in C:\Repos\AnalyticsCollectors\Collectors\AnalyticsCollector\KustoService\AzureDataExplorerService.cs:line 150
   at AnalyticsCollector.AzureDataExplorerService.<ExecuteQuery>d__8.MoveNext() in C:\Repos\AnalyticsCollectors\Collectors\AnalyticsCollector\KustoService\AzureDataExplorerService.cs:line 108
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at AnalyticsCollector.AzDevopsWaterMark.ReadWaterMark(String entityName) in C:\Repos\AnalyticsCollectors\Collectors\AnalyticsCollector\Entities\AzDevopsWaterMark.cs:line 35
   at AnalyticsCollector.AzDevopsReleaseDeployment.IngestData(AzDevopsWaterMark azureAzDevopsWaterMark) in C:\Repos\AnalyticsCollectors\Collectors\AnalyticsCollector\Entities\AzDevopsReleaseDeployment.cs:line 32
Cannot read database due to System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

That is because the call to get database list returns empty list even when there is a data base inside. 

Clearing %AppData%\Kusto\tokenCache.data is an essential step for it. We should show this advise if we run into this error

@khilan2goel - FYI

**Comment by khilangoel** [comment]
I have added in error message itself
